using System.Reflection;
using System.Reflection.Emit;
using System.Runtime.Loader;
namespace Brady.BitzerDesktopHost;
internal static class HhkBitzerDllInspector{
static readonly OpCode[] O=new OpCode[256],T=new OpCode[256];
static HhkBitzerDllInspector(){foreach(var f in typeof(OpCodes).GetFields(BindingFlags.Public|BindingFlags.Static)){if(f.GetValue(null)is not OpCode x)continue;ushort v=(ushort)x.Value;if(v<256)O[v]=x;else if((v&0xff00)==0xfe00)T[v&255]=x;}}
public static int Run(string root){var dir=Path.Combine(Path.GetTempPath(),"brady-bitzer-inspect","hhk-candidates");var dll=Path.Combine(dir,"Calculation.dll");if(!File.Exists(dll)){Console.Error.WriteLine("Calculation.dll not found.");return 81;}AssemblyLoadContext.Default.Resolving+=(c,n)=>{foreach(var d in new[]{dir,Path.GetFullPath(Path.Combine(root,"..","selection")),root}){var p=Path.Combine(d,n.Name+".dll");if(File.Exists(p))try{return c.LoadFromAssemblyPath(p);}catch{}}return null;};try{var a=AssemblyLoadContext.Default.LoadFromAssemblyPath(dll);var calc=a.GetType("Bitzer.CalculationHHK",true)!;var cs=calc.GetMethods(BindingFlags.Public|BindingFlags.NonPublic|BindingFlags.Instance|BindingFlags.Static|BindingFlags.DeclaredOnly).First(x=>x.Name=="CalculateSingle"&&x.GetMethodBody()!=null);var inv=Find(cs,"Invoke","Bitzer.BitzerFunction")??throw new MissingMethodException("Invoke");var bf=inv.DeclaringType!;Console.WriteLine("BITZER DLL GETTER");Dump(bf.GetMethod("get_BitzerDLL",BindingFlags.Public|BindingFlags.NonPublic|BindingFlags.Instance|BindingFlags.Static));Console.WriteLine("BITZERDLL MEMBERS");foreach(var f in bf.GetFields(BindingFlags.Public|BindingFlags.NonPublic|BindingFlags.Instance|BindingFlags.Static).Where(x=>x.Name.Contains("Bitzer",StringComparison.OrdinalIgnoreCase)||x.FieldType.FullName?.Contains("IBitzer")==true))Console.WriteLine($"FIELD {f.FieldType.FullName} {f.Name}");Console.WriteLine("Safety: metadata/IL only; getter not invoked; no calculation executed.");return 0;}catch(Exception e){Console.Error.WriteLine($"{e.GetType().Name}: {e.Message}");return 82;}}
static void Dump(MethodBase? m){if(m==null){Console.WriteLine("METHOD <not found>");return;}Console.WriteLine($"METHOD {m.DeclaringType?.FullName}.{m.Name} | {m}");var b=m.GetMethodBody();if(b==null){Console.WriteLine(" BODY <none/native/external>");return;}foreach(var x in D(m))Console.WriteLine($" IL_{x.Item1:X4}: {x.Item2.Name} {x.Item3}");}
static MethodBase? Find(MethodBase m,string n,string t){foreach(var x in R(m)){if(x.Item1.OperandType!=OperandType.InlineMethod)continue;try{var q=m.Module.ResolveMethod(x.Item2,m.DeclaringType?.GetGenericArguments(),m.IsGenericMethod?m.GetGenericArguments():null);if(q?.Name==n&&q.DeclaringType?.FullName==t)return q;}catch{}}return null;}
static IEnumerable<(OpCode,int)> R(MethodBase m){var il=m.GetMethodBody()!.GetILAsByteArray()!;int p=0;while(p<il.Length){OpCode o=il[p++]==0xfe?T[il[p++]]:O[il[p-1]];int n=S(o.OperandType,il,p);if(n<0||p+n>il.Length)yield break;yield return(o,n>=4?BitConverter.ToInt32(il,p):0);p+=n;}}
static List<(int,OpCode,string)> D(MethodBase m){var il=m.GetMethodBody()!.GetILAsByteArray()!;var r=new List<(int,OpCode,string)>();int p=0;while(p<il.Length){int z=p;OpCode o=il[p++]==0xfe?T[il[p++]]:O[il[p-1]];int n=S(o.OperandType,il,p);if(n<0||p+n>il.Length)break;string s="";try{if(o.OperandType is OperandType.InlineMethod or OperandType.InlineField or OperandType.InlineType or OperandType.InlineTok){var q=m.Module.ResolveMember(BitConverter.ToInt32(il,p),m.DeclaringType?.GetGenericArguments(),m.IsGenericMethod?m.GetGenericArguments():null);s=(q?.DeclaringType?.FullName??"")+"."+q?.Name;}else if(o.OperandType==OperandType.InlineString)s=m.Module.ResolveString(BitConverter.ToInt32(il,p));}catch{}r.Add((z,o,s));p+=n;}return r;}
static int S(OperandType o,byte[]b,int p)=>o switch{OperandType.InlineNone=>0,OperandType.ShortInlineBrTarget or OperandType.ShortInlineI or OperandType.ShortInlineVar=>1,OperandType.InlineVar=>2,OperandType.InlineI or OperandType.InlineBrTarget or OperandType.InlineField or OperandType.InlineMethod or OperandType.InlineSig or OperandType.InlineString or OperandType.InlineTok or OperandType.InlineType or OperandType.ShortInlineR=>4,OperandType.InlineI8 or OperandType.InlineR=>8,OperandType.InlineSwitch=>4+4*BitConverter.ToInt32(b,p),_=>-1};}